# Generated by Django 4.0.3 on 2022-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tashkilotlar',
            name='t_inn',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tashkilotlar',
            name='t_shxr',
            field=models.IntegerField(default=0),
        ),
    ]
